### ISSUE TITLE
Feature Request: Add support for crosstalk

### ISSUE THREAD

**Issue by JustGitting** [r-world-devs/cohortBuilder#33]
Hi,

It would be great if cohortBuilder / shinyCohortBuilder supported the crosstalk (https://rstudio.github.io/crosstalk/) package.

This would enable the filters from cohortBuilder to update other htmlwidgets (http://htmlwidgets.org/) widgets.

**Comment by galachad** [comment]
This will not be possible to support. The cohort Builder relay on R runtime and shinyCohortBuild is just a gui layer for cohortBuilder. It's possible to use cohortBuilder and shinyCohortBuilder with webr.

**Comment by JustGitting** [comment]
Hi @galachad,

I'm not familiar with webr. Are you be able to explain how webr could be used to allow cohortbuilder to interact with other htmlwidegets?
